### ISSUE TITLE
Want to create react todo project dynamic project which is different from other todo 

### ISSUE THREAD

**Issue by harshalhonde21** [sadanandpai/frontend-mini-challenges#228] opened 2023-10-14 09:11 UTC
All the todo are disapper after the adding and refreshing we should add localstorage to do the project dyanamic

**Comment by harshalhonde21** [comment] 2023-10-14 09:12
assign this issue to me

**Comment by arpansaha13** [comment] 2023-10-14 13:43
Duplicate of issue #185 

You are already assigned in that issue.

**Comment by arpansaha13** [comment] 2023-10-14 13:45
You may open a PR to add this change

**Comment by arpansaha13** [comment] 2023-10-14 13:47
@harshalhonde21 I am closing this issue since it is a duplicate of another.
You can consider #185 as the issue for your PR

**Closed by arpansaha13** 2023-10-14 13:47 UTC
Labels: duplicate
